spring:
  session:
    store-type: hash_map
  thymeleaf:
    cache: false
---
elasticsearch:
  cluster: elasticsearch-price-parity
  hosts:
    - http://123.206.103.124:9200
    - http://115.159.143.242:9200
---
system:
  debug: false


