spring:
  session:
    store-type: hash_map
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
---
elasticsearch:
  cluster: elasticsearch-price-parity
  hosts:
    - http://123.206.103.124:9200
    - http://115.159.143.242:9200
---
system:
  debug: false
  heartURL: http://localhost:8020/beat

#server:
#  port: 1111
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url.defaultZone: http://localhost:${server.port}/eureka/


